valid_input={
  "txn_id":"TXN00088187",
  "timestamp": "2025-01-01T00:03:00",
  "sender_id": 102,
  "receiver_id": 341,
  "sender_upi_domain": "@oksbi",
  "receiver_upi_domain": "@okaxis",
  "sender_account_age_days": 320,
  "receiver_account_age_days": 120,
  "amount": 2500,
  "sender_city": "Bangalore",
  "receiver_city": "Mumbai",
  "device_changed": 1,
  "ip_changed": 0,
  "city_changed": 1,
  "failed_logins_last_24h": 4,
  "txn_count_last_1h": 8,
  "txn_count_last_24h": 20,
  "is_new_beneficiary": 1,
  "merchant_category": "Shopping",
  "amount_to_average_ratio": 3.5,
  "distance_from_last_transaction": 180,
  "payday_intensity": 0.8,
  "month": 6,
  "day_of_month": 30,
  "hour_of_day": 14,
  "day_of_week": 6,
  "is_festival": 0
}